#  Copyright (C) 2018-2019 LEIDOS.
# 
#  Licensed under the Apache License, Version 2.0 (the "License"); you may not
#  use this file except in compliance with the License. You may obtain a copy of
#  the License at
# 
#  http://www.apache.org/licenses/LICENSE-2.0
# 
#  Unless required by applicable law or agreed to in writing, software
#  distributed under the License is distributed on an "AS IS" BASIS, WITHOUT
#  WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied. See the
#  License for the specific language governing permissions and limitations under
#  the License.

# Docker Compose Spec Version
version: '2'

services:
  roscore:
    image: usdotfhwastol/carma-base:2.8.3
    network_mode: host
    container_name: roscore
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/.ros:/home/carma/.ros
    restart: always
    command: roscore
  platform:
    image: usdotfhwastol/carma:2.8.3
    network_mode: host
    container_name: platform
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch carma saxton_cav_docker.launch
  mock-lateral-control-driver:
    image: usdotfhwastol/carma:2.8.3
    network_mode: host
    container_name: carma-mock-lateral-control-driver
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 --  rosrun carma lateral_control_driver gov.dot.fhwa.saxton.carma.lateralcontroldriver.LateralControlDriver
  cohda_dsrc_driver:
    image: usdotfhwastol/carma-cohda-dsrc-driver:1.0.0
    container_name: carma-cohda-dsrc-driver
    network_mode: host
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch dsrc_driver dsrc_node.launch remap_ns:=/saxton_cav/drivers
  cadillac-srx-2013-can-driver:
    image: usdotfhwastol/carma-cadillac-srx-2013-can-driver:1.0.1
    container_name: carma-cadillac-srx-2013-can-driver
    network_mode: host
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch srx_can_driver srx_can_driver_socketcan.launch remap_ns:=/saxton_cav/drivers srx_can_can_device:=can2
  cadillac-srx-2013-objects-driver:
    image: usdotfhwastol/carma-cadillac-srx-2013-objects-driver:1.0.2
    container_name: carma-cadillac-srx-2013-objects-driver
    network_mode: host
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch srx_objects srx_objects_socketcan.launch remap_ns:=/saxton_cav/drivers srx_objects_can_device:=can0
  cadillac-srx-2013-controller-driver:
    image: usdotfhwastol/carma-cadillac-srx-2013-controller-driver:1.0.2
    container_name: carma-cadillac-srx-2013-controller-driver
    network_mode: host
    volumes_from: 
      - container:carma-config:ro
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch srx_controller srx_controller.launch remap_ns:=/saxton_cav/drivers srx_controller_can_device:=can1
  torc-pinpoint-driver:
    image: usdotfhwastol/carma-torc-pinpoint-driver:1.0.7
    container_name: carma-torc-pinpoint-driver
    network_mode: host
    volumes_from: 
      - container:carma-config:ro
    environment:
      - ROS_IP=192.168.88.10
    volumes:
      - /opt/carma/logs:/opt/carma/logs
      - /opt/carma/.ros:/home/carma/.ros
      - /opt/carma/vehicle/HostVehicleParams.yaml:/opt/carma/params/HostVehicleParams.yaml
    command: wait-for-it.sh localhost:11311 -- roslaunch pinpoint pinpoint.launch remap_ns:=/saxton_cav/drivers
